### ISSUE TITLE
Doesn't work env in settings block with drone version 1

### ISSUE THREAD

**Issue by theshamuel** [appleboy/drone-scp#101]
Hi there,
I tried to use this block in .drone.yml from official docs http://plugins.drone.io/appleboy/drone-scp/:
<pre>
....
  deploy:
    image: appleboy/drone-scp:1.5-linux-amd64
    settings:
      host: `MY_SERVER`
      username: `MY_USER`
      password: test
      port: 22
      command_timeout: 2m
      target: `FILE`
      source: `FILE`
...
</pre>
**I got an error "Error: missing server host "**

after changing the conf to :
<pre>
....
  deploy:
    image: appleboy/drone-scp:1.5-linux-amd64
    host: `MY_SERVER`
    username: `MY_USER`
    password: test
    port: 22
    command_timeout: 2m
    target: `FILE`
    source: `FILE`
...
</pre>
everything started to work fine.
it seems the block settings does not work

**Comment by appleboy** [comment]
What is your drone version? 1.x?

**Comment by theshamuel** [comment]
yup

**Comment by appleboy** [comment]
Can you also try the `latest` version of drone?

The following only support 0.8 or under version.

```yaml
  deploy:
    image: appleboy/drone-scp:1.5-linux-amd64
    host: `MY_SERVER`
    username: `MY_USER`
    password: test
    port: 22
    command_timeout: 2m
    target: `FILE`
    source: `FILE`
```
