### ISSUE TITLE
Unable to pass password as secret using drone-scp in drone 0.8.0 version

### ISSUE THREAD

**Issue by vinodkrishnan1310** [appleboy/drone-scp#116]
Below is the snippet of .drone.yml, I am using for drone-scp. I have added secrets SSH_USERNAME,SSH_PASSWORD in Drone UI - Secret section. Please assist here, I am stuck here.  

```
peanut-scp-action:
    image: appleboy/drone-scp
    host: XXXX-XXXXX.XYZ.com
    port: 22
    secrets: [ SSH_USERNAME, SSH_PASSWORD ]
    target: $HOME/xxxxx-prd/
    source: /xxxxxx/src/git.xxxxxx.com/xxxxxxxx/xxxxx/*
    when:
      event: [ push ]
      branch: [ master ]
```
