### ISSUE TITLE
 wildcard pattern of source list copy errors using drone cron

### ISSUE THREAD

**Issue by SaneHe** [appleboy/drone-scp#118]
one pipeline, same buids
1、 test server scp conf
```yml
- name: test
  image: appleboy/drone-scp
  settings:
    host:
      from_secret: test-host
    username:
      from_secret: test-user
    key:
      from_secret: test-ssh
    port:
      from_secret: test-port
    command_timeout: 5m
    target: 
      - /data/www/sane/
    source:
      - ./dist/*
  when:
    status: [success]
    event:
    - push
    branch:
    - test
```
2、preview server scp conf
```yml
- name: qa
  image: appleboy/drone-scp
  settings:
    host:
      from_secret: preview-host
    username:
      from_secret: preview-user
    key:
      from_secret: preview-ssh
    port:
      from_secret: preview-port
    command_timeout: 5m
    target: 
      - /data/www/sane/
    source:
      - ./dist/*
  when:
    status: [success]
    event:
    - cron
```

#### result

test server
![image](https://user-images.githubusercontent.com/28290710/89114403-76c15080-d4ae-11ea-93a2-d56859876027.png)

preview server
![image](https://user-images.githubusercontent.com/28290710/89114410-98bad300-d4ae-11ea-8476-cfd3b131472c.png)

crone trigger wrong？
