### ISSUE TITLE
Support multiple hosts with different passwords ?

### ISSUE THREAD

**Issue by medivh-jay** [appleboy/drone-scp#120]
Hello , Thanks for your scp tool ,  It saved me a lot of work!

judging from the plug-in documentation, this plugin support multiple hosts, but it seems that all hosts must have the same SSH password， can it support each host to use a different password? 

Thanks!

**Comment by imkratos** [comment]
UP , I need same features, Thanks.

**Comment by Wolf2789** [comment]
Why not just add duplicate steps for hosts with different passwords?
Templating could be helpful there:
```
steps:
...
- name: Settings template
  image: appleboy/drone-scp
  settings: &scp_settings
    source: ./
    target: /tmp/target
  when:
    event:
      - template # Making sure here, the step never executes

- name: Deploy 1
  image: appleboy/drone-scp
  settings:
    <<: *scp_settings
    host:
      - 127.0.0.1
    user: admin
    password:
      from_secret: PASSWORD_1

- name: Deploy 2
  image: appleboy/drone-scp
  settings:
    <<: *scp_settings
    host:
      - 127.0.0.2
    user: admin
    password:
      from_secret: PASSWORD_2
```
