### ISSUE TITLE
2021/03/30 10:23:07 error copy file to dest: xxxxxxxxxxxx, error message: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain

### ISSUE THREAD

**Issue by zeronacer** [appleboy/drone-scp#124]
```
2021/03/30 10:23:07 error copy file to dest: xxxxxxxxxxxx, error message: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
```
It seems like the plugin doesn't use my password? This is my deploy step:
```
image: appleboy/drone-scp
settings:
    host: xxxxxxxxx
    username: xxxxxxxxx
    password:
        from_secret: ssh_password
    port: 22
    target: xxxxxxx
    source:
        - xxxxxxx
        - xxxxxxx
```
Maybe someone can help me.
