### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by Gaz492** [appleboy/drone-scp#125]
I'm getting the following message on the deploy stage I have.

```
latest: Pulling from appleboy/drone-scp
Digest: sha256:587ae4156fdc02e26f9b0d31f151c43b0c142942dca81623aa375d0cd44755ab
Status: Image is up to date for appleboy/drone-scp:latest
tar all files into /tmp/315353600/Mgql08j0T0.tar
scp file to server.
create folder /home/gaz/web/ytmv
untar file Mgql08j0T0.tar
drone-scp error:  dial tcp ip:22: connect: connection refused
drone-scp rollback: remove all target tmp file
remove file Mgql08j0T0.tar
2021/05/07 17:57:51 dial tcp ip:22: connect: connection refused
```

My build file is as follows

```
kind: pipeline
type: docker
name: Build & Deploy

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: node:lts-alpine3.13
    commands:
    - npm install
    - npm run build
  - name: deploy
    image: appleboy/drone-scp
    settings:
      host: ip
      user: gaz
      key:
        from_secret: ssh_key
      command_timeout: 2m
      target: /home/gaz/web/ytmv
      source:
        - dist/*
```

I tried using the scp command on the server its running on and that was able to connect so I'm not really sure what the issue is.
