### ISSUE TITLE
Source list wildcard doesn't seem to work

### ISSUE THREAD

**Issue by tim-the-arcane** [appleboy/drone-scp#127]
Hi all!

I started using this image as plugin for Drone CI to deploy my Svelte app on the production web server.

```yaml
kind: pipeline
type: docker
name: default

steps:
- name: pull and build
  image: node
  commands:
  - npm install
  - npm run build

- name: deploy to server
  image: appleboy/drone-scp
  settings:
    host:
      from_secret: ssh_host
    username:
      from_secret: ssh_user
    key:
      from_secret: ssh_key
    port: 22
    command_timeout: 2m
    target:
      from_secret: ssh_target_dir
    source:
      - build/*
```

It already works but it uploads the whole `build` folder instead of the **contents** of the build folder:

![image](https://user-images.githubusercontent.com/10296479/134524423-dad113dd-645a-4abf-aa15-1d4240294169.png)

Is there any setting I'm missing? Thanks a lot for taking your time to read my issue!

**Comment by tim-the-arcane** [comment]
Hi @serxoz,

indeed I got it working by adding the option `strip_components` after the other scp settings like this:

```yml
kind: pipeline
type: docker
name: default

steps:
  - name: pull and build
    image: node
    commands:
      - npm install
      - npm run build

  - name: deploy to production server
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_user
      key:
        from_secret: ssh_key
      port: 22
      command_timeout: 2m
      target:
        from_secret: ssh_target_dir
      source: ./build/*
      strip_components: 1
    when:
      branch:
        - main
```

Since this change it works for me.

Maybe a better explanation of this option would help in the documentation?
