### ISSUE TITLE
the [overwrite] properties why didn't work?

### ISSUE THREAD

**Issue by werewolf666** [appleboy/drone-scp#138]
## desc:
source file list:
```
docker-compose.yml
restart.sh
stop.sh
```
I try 2 ways,the problem still alive.

* first way:
i compress them to  deploy.tar.gz as a one file ,then configure .drone.yaml,like this
the .drone.yaml setting:
```
image： appleboy/drone-scp:1.6.4  
target: /data-test/web/${DRONE_REPO_NAME}
source:
    ./deploy.tar.gz
overwrite: false
```
in target dir,the name is deploy.tar.gz is exists.but everytime overwrited by drone-scp.

* second way:
 not compress them like this
```
target: /data-test/web/${DRONE_REPO_NAME}
source:
  - ./deploy/docker-compose/docker-compose.yml
  - ./deploy/docker-compose/restart.sh
  - ./deploy/docker-compose/stop.sh
strip_components: 3
overwrite: false
```
in target dir,3 files is exists,but everytime overwrited by drone-scp to.

## so,is my usage is wrong or other questions?
think you very much.

**Comment by appleboy** [comment]
Please ignore the file using `!` symbol. Try the following config.

```yaml
target: /data-test/web/${DRONE_REPO_NAME}
source:
  - ./deploy
  - !./deploy/docker-compose/docker-compose.yml
  - !./deploy/docker-compose/restart.sh
  - !./deploy/docker-compose/stop.sh
strip_components: 3
```
