### ISSUE TITLE
When the configuration parameter rm is true, an error will be generated

### ISSUE THREAD

**Issue by shuyudao** [appleboy/drone-scp#140]
settings.rm: true #**If true : Process exited with status 1** ; **If false : ✅ Successfully...**
```
settings:
    host: ***
    port: 22
    username: root
    password: 
      from_secret: root_password
    strip_components: 1
    overwrite: true
    rm: true #If true : Process exited with status 1
    source: ./dist/*
    target: /target
```

console logs
```
tar all files into /tmp/297369615/ZOqVuExJPx.tar
scp file to server.
Remove target folder: ***
drone-scp error:  Process exited with status 1
drone-scp rollback: remove all target tmp file
remove file ZOqVuExJPx.tar
2022/10/30 20:19:41 Process exited with status 1
```
