### ISSUE TITLE
getKeyFile error: open {ssh_key} permission denied

### ISSUE THREAD

**Issue by theonedemon** [appleboy/drone-scp#186]
after update container to 1.6.12 not working via ssh_key over volumes:
```
...
- name: test
      image: appleboy/drone-scp:1.6.12
      volumes:
          - name: id_rsa
            path: /home/deploy/id_rsa
      settings:
          host:
              - 1.1.1.1
          user: root
          port: 22
          key_path: /home/deploy/id_rsa
          overwrite: true
          target: /home/test
          source:
              - /1.tar
...
volumes:
    - name: id_rsa
      host:
          path: /var/keys/id_rsa
```

output commands:
```
drone-scp version: v1.6.12
tar all files into /tmp/icdbJewxtu.tar.gz
tar: removing leading '/' from member names
2023/12/26 22:44:31 getKeyFile error: open /home/deploy/id_rsa: permission denied
drone-scp error:  error copy file to dest: 1.1.1.1, error message: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
```
