### ISSUE TITLE
Templates not evaluating

### ISSUE THREAD

**Issue by josegomezr** [appleboy/drone-scp#24]
According to DroneCI Docs on [Drone-SCP](http://plugins.drone.io/appleboy/drone-scp/#template-reference) its possible to use templates. 

Nevertheless, those aren't evaluated at all. For example your Plugin [Drone-Telegram](https://github.com/appleboy/drone-telegram) have those too, and they evaluate just perfectly.

It'll be great to have them working for parameters like `target`, `username` or `key`.

### Example
```yml
pipeline:
  build:
    image: node:alpine
    commands:
      - npm install
      - npm run build

  deploy_scp:
    image: appleboy/drone-scp
    host: deploy.host
    target: /var/www/deploy/{{repo.owner}}/{{repo.name}}
    source: ./public
    rm: true
    username: deploy
    password: deploy
```

Will create a folder called (literally) `/var/www/deploy/{{repo.owner}}/{{repo.name}}`.

**Comment by appleboy** [comment]
Hi @josegomezr 

You can try the following config.

```
target: /var/www/deploy/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}
```

ref: http://readme.drone.io/usage/environment-reference/

**Comment by appleboy** [comment]
I close this issue now. Please feel free to reopen the issue if you have the same problem.

**Comment by cyberb** [comment]
Could you provide an example in the documentation:
http://plugins.drone.io/appleboy/drone-scp/

**Comment by appleboy** [comment]
@cyberb 

See the sample in http://plugins.drone.io/appleboy/drone-scp:

```
- name: scp files
  image: appleboy/drone-scp
  settings:
    host: example.com
    target: /home/deploy/web
    source: release.tar.gz
```

I will update it.
