### ISSUE TITLE
Very slow deployment

### ISSUE THREAD

**Issue by CupCakeArmy** [appleboy/drone-scp#81]
This may not be an Issue, but the deployment is taking veeery long.

<img width="758" alt="screen shot 2018-07-24 at 12 44 52" src="https://user-images.githubusercontent.com/14948823/43133535-6ef3559e-8f3f-11e8-8c09-ea51b392c9b5.png">

Is this normal? the server itself is pretty fast and the connection should not be the issue.
am I doing something wrong?

This is the source file used:
```yml
pipeline:
  
  copy:
    image: appleboy/drone-scp
    host: mydomain.com
    username: myUser
    port: 1234
    secrets: [ ssh_key ]
    target: /my/target/dir
    source: ./*
    rm: true
```
