### ISSUE TITLE
1.0.0-rc.1 missing ssh config (Host, Username)

### ISSUE THREAD

**Issue by weisd** [appleboy/drone-scp#84]
when I use drone 1.0.0-rc.1, the yml config is
```yml
- name: scp
  image: appleboy/drone-scp
  host: "xxx.xxx.xxx.xxx"
  port: 22
  target: /path/to
  source: test
  username: drone
  secrets: [ ssh_password ]
```
then I got the error 

```
missing ssh config (Host, Username)
```

**Comment by appleboy** [comment]
I will test the new drone version asap.

**Comment by replicant0wnz** [comment]
Invalid yaml, should look like this

```yaml
- name: push
  image: appleboy/drone-scp
  settings:
    host: xxx
    username: drone
    ssh_key:
      from_secret: drone
    source: dist
    target: /home/drone/dist
```

**Comment by appleboy** [comment]
@weisd Please try the @replicant0wnz solution.

**Comment by yiranzai** [comment]
@appleboy  
@replicant0wnz 
I have encountered this error
I use drone 1.0.0-rc.5, the yml config is
```
- name: deploy
  image: appleboy/drone-scp
  when:
    status:
    - success
  settings:
    host:
      from_secret: deploy_host
    port:
      from_secret: deploy_port
    key:
      from_secret: deploy_rsa
    username:
      from_secret: deploy_username
    target:
      from_secret: web_path
    source: public
    strip_components: 1
```
then I got the same error

```
missing ssh config (Host, Username)
```

**Comment by appleboy** [comment]
Please try the plain text like below:

```
  - name: scp
    image: appleboy/drone-scp
    pull: true
    settings:
      host: example.com
      username: deploy
      key:
        from_secret: deploy_key
      target: /home/deploy/gobento
      rm: true
      source:
        - release/*
        - Dockerfile
        - docker-compose.yml
```
