### ISSUE TITLE
Do the multiple host support from_secret?

### ISSUE THREAD

**Issue by mrxliu** [appleboy/drone-scp#97]
The following example(github readme.md):

```yml
pipeline:
  scp:
    image: appleboy/drone-scp
    settings:
      host:
        - example1.com
        - example2.com
      username: ubuntu
```

But i want to like the following example, can anyone help me ?

```yml
pipeline:
  scp:
    image: appleboy/drone-scp
    settings:
      host:
        - from_secret: EXAMPLE_HOST1
        - from_secret: EXAMPLE_HOST2
      username: ubuntu
```

**Comment by appleboy** [comment]
@mrxliu Try the following config:


```yaml
pipeline:
  scp:
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: EXAMPLE_HOST
      username: ubuntu
```

and set the `EXAMPLE_HOST` value as `example01.com,example02.com`.
