### ISSUE TITLE
How to copy just folder content?

### ISSUE THREAD

**Issue by artemanufrij** [appleboy/drone-scp#99]
Hey guys,
I have a question. How can I copy just content of a folder into target?

What I need: `/var/www/drone/app/webplay/files.xyz`
What I get: `/var/www/drone/app/webplay/dist/files.xyz`

Here is my current script
```
- name: deploy
  image: appleboy/drone-scp
  settings:
    host:
      from_secret: drone_server_host
    username:
      from_secret: drone_server_user
    password:
      from_secret: drone_server_pass
    port:
      from_secret: drone_server_port
    command_timeout: 2m
    rm: true
    target: /var/www/drone/app/webplay
    source:
    - dist/*
```

best regards
Artem
